name: Run PHP Static Analysis

on: pull_request

jobs:
  code-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

#      - name: Code Standards Test
#        uses: docker://aligent/code-standards-pipe-php:8.1
#        env:
#          STANDARDS: "Magento2"
#          SKIP_DEPENDENCIES: "true"
#          BITBUCKET_PR_DESTINATION_BRANCH: "3.x"
